spring:
 application:
  name: eureka-server

server:
 port: 8081

eureka:
 client:
  registerWithEureka: false
  fetchRegistry: false
  service-url:
   defaultZone: http://localhost:8081/eureka
  server:
  waitTimeInMsWhenSyncEmpty: 0			